"""empty message

Revision ID: 3458476a2b57
Revises: 4aefedb1fc45
Create Date: 2025-04-29 16:27:07.205187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3458476a2b57'
down_revision = '4aefedb1fc45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('fav_user_id_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fav_user_id_fk'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites')
    # ### end Alembic commands ###
