"""empty message

Revision ID: ec6e36768803
Revises: 2fdcf5cea774
Create Date: 2025-04-05 04:15:42.464568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6e36768803'
down_revision = '2fdcf5cea774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_constraint('favourite_fav_user_id_fk_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['fav_user_id_fk'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favourite_fav_user_id_fk_fkey', 'users', ['fav_user_id_fk'], ['id'])

    # ### end Alembic commands ###
